language: android
jdk:
  - oraclejdk8
sudo: required
dist: trusty
env:
  global:
    - BRANCH_NAME=master
    - ANDROID_BUILD_TOOLS=29.0.3
android:
  components:
    - android-29
    - build-tools-$ANDROID_BUILD_TOOLS
    - extra-google-google_play_services
  licenses:
    - ".+"
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
before_install:
- openssl aes-256-cbc -K $encrypted_bbe4408b9dd8_key -iv $encrypted_bbe4408b9dd8_iv -in demotravistoday-8c218be67d1f.json.enc -out /tmp/demotravistoday-8c218be67d1f.json -d
  - yes | sdkmanager "platforms;android-29"
  - mkdir "$ANDROID_HOME/licenses" || true
before_script:
  - env
  - gcloud auth activate-service-account traviscidemofinal@demotravistoday.iam.gserviceaccount.com --key-file=/tmp/demotravistoday-8c218be67d1f.json --project=travisdemo-646f8

script:
  - ./firebase1.sh